# Generated by Django 3.2 on 2021-05-03 22:45

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=20)),
                ('number', phone_field.models.PhoneField(blank=True, default=0, help_text='Contact phone number', max_length=31)),
                ('business', models.CharField(default='NA', max_length=40)),
                ('service', models.CharField(default='NA', max_length=30)),
                ('notes', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='NA', max_length=40)),
                ('address', models.CharField(default='NA', max_length=40)),
                ('city', models.CharField(default='NA', max_length=20)),
                ('state', models.CharField(default='NA', max_length=20)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('square_feet', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=20)),
                ('budget', models.IntegerField(default=0)),
                ('notes', models.CharField(default='NA', max_length=200)),
                ('home', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.home')),
            ],
        ),
    ]
