# Generated by Django 3.2 on 2021-04-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('business', models.CharField(default='NA', max_length=40)),
                ('service', models.CharField(default='NA', max_length=30)),
                ('notes', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='NA', max_length=40)),
                ('address', models.CharField(default='NA', max_length=40)),
                ('city', models.CharField(default='NA', max_length=20)),
                ('state', models.CharField(default='NA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=20)),
                ('budget', models.IntegerField(default=0)),
                ('notes', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
