# Generated by Django 3.2 on 2021-05-05 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='NA', max_length=40)),
                ('address', models.CharField(default='NA', max_length=40)),
                ('city', models.CharField(default='NA', max_length=20)),
                ('state', models.CharField(default='NA', max_length=20)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('square_feet', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=20)),
                ('budget', models.IntegerField(default=0)),
                ('notes', models.CharField(default='NA', max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=20)),
                ('phone', models.BigIntegerField(default=1111111111)),
                ('business', models.CharField(default='NA', max_length=40)),
                ('service', models.CharField(default='NA', max_length=30)),
                ('notes', models.CharField(default='NA', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
