# Generated by Django 3.2 on 2021-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='nickname',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='home',
            name='projects',
            field=models.ManyToManyField(to='main_app.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='business',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='notes',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='service',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
