# Generated by Django 3.2 on 2021-04-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='square_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='year_built',
            field=models.IntegerField(default=0),
        ),
    ]
