# Generated by Django 3.2 on 2021-05-03 22:48

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=phone_field.models.PhoneField(blank=True, default=0, max_length=31),
        ),
    ]
