# Generated by Django 3.2 on 2021-05-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_contacts_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='number',
            new_name='phone',
        ),
    ]
