# Generated by Django 3.2 on 2021-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210508_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='NA', help_text='Project name', max_length=20),
        ),
    ]
