# Generated by Django 3.2 on 2021-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='descritption',
            field=models.CharField(default='No Description', max_length=200),
        ),
    ]
