# Generated by Django 3.2 on 2021-05-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_photo_descritption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='descritption',
        ),
    ]
