# Generated by Django 3.2 on 2021-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_photo_descritption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('company', models.CharField(default=' ', max_length=40)),
                ('description', models.CharField(default=' ', max_length=200)),
                ('cost', models.IntegerField(default=1)),
            ],
        ),
    ]
