# Generated by Django 3.2 on 2021-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='location',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
