# Generated by Django 3.2 on 2021-05-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_budget_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='location',
            new_name='house',
        ),
    ]
