# Generated by Django 3.2 on 2021-05-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
